### ISSUE TITLE
Thread is getting blocked when inserting 10,000 records

### ISSUE THREAD

**Issue by paultnp** [shaps80/Stack#3]
When I try to insert 10,000 record the screen gets blocked and I can not go any where in the screen. Please let me know how will the record be inserted without blocking the screen.

I used below code,

In viewDidLoad
Stack.configureDefaults { (config) -> () in
            config.stackType = .ParentChild
            config.persistenceType = .SQLite 
        }

And on button click
        let stack = Stack.defaultStack()
        stack.write({ (transaction) -> Void in
            for i in 0...10000
            {
                let post = try transaction.insert() as Post
                post.postby = name as String
                post.postText = "Hello"
                print("(i) Stack: Inserted -- (post) -- %@", NSThread.currentThread())
            }
        }) { (error) -> Void in
            if error != nil { print(error) }
        }

**Comment by shaps80** [comment]
First off, apologies for not seeing this until now. Looks like GitHub didn't notify me of this issue so I'm only just seeing it.

--- 

`write` transactions are not async. Meaning they are executed on the current thread. This is an intended design pattern to ensure the caller can decide on which thread or queue they want their code to execute. Similarly to how CoreData works itself.

Therefore in this scenario you would need to wrap the `write` transaction inside of an operation or `dispatch_async` call.

FYI when using importing large data sets, its better NOT to use the parent-child setup because this will always block the main thread when CoreData merges the changes to your UI context.

Instead, use the manual merge stack which can mean the difference from 20s to 0.1s to merge changes into the UI context.

> Note: This is not specific to my implementation, its just how parent-child context merges are performed internal to CoreData.

---

I have an update coming soon, which includes full Swift 3 support as well as iOS 10 CoreData updates. In fact it won't be compatible with iOS <10. However it will make use of the built in Type Safety and better stack management that the SDK is now providing, but with my familiar interface that abstracts away the CoreData details.
